name: video_editor
version: 4.0.0
description: |
 A flutter package for editing video with fully customizable UI.
 Supports crop, trim, rotation and cover selection.
 Provides commands to run in order to export the video or cover.
repository: https://github.com/LeGoffMael/video_editor

environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1
  path: ^1.8.0 # update to `1.8.1` causes #79
  path_provider: ^2.0.12
  transparent_image: ^2.0.1 # show fade-in placeholder in thumbnails generation
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Video editor demo'
    path: assets/demo_thumb.webp